import { APP_ENTRANCE_S } from "@/components/session/intro/intro-constants";

export type IntroAppAccent = "nova" | "bite" | "frame" | "apex";

export type IntroAppConfig = {
  id: string;
  label: string;
  accent: IntroAppAccent;
  enterAt: number;
  imageSrc: string;
  imageAlt: string;
  desktop: { x: string; y: string; rotate: number; scale: number; z: number };
  mobile: { x: string; y: string; rotate: number; scale: number; z: number };
  entrance: {
    fromX: string;
    fromY: string;
    fromRotate: number;
    glow: string;
  };
};

export const INTRO_CINEMATIC_APPS: IntroAppConfig[] = [
  {
    id: "nova",
    label: "NOVA",
    accent: "nova",
    enterAt: APP_ENTRANCE_S.nova,
    imageSrc: "/intro/nova.png",
    imageAlt: "Nova fashion store generated by Vodex",
    desktop: { x: "-36%", y: "-32%", rotate: 0, scale: 0.94, z: 12 },
    mobile: { x: "-48%", y: "-36%", rotate: 0, scale: 1, z: 12 },
    entrance: { fromX: "-115%", fromY: "0%", fromRotate: -12, glow: "purple" },
  },
  {
    id: "bite",
    label: "bite.",
    accent: "bite",
    enterAt: APP_ENTRANCE_S.bite,
    imageSrc: "/intro/bite.png",
    imageAlt: "Bite food delivery app generated by Vodex",
    desktop: { x: "36%", y: "-32%", rotate: 0, scale: 0.92, z: 14 },
    mobile: { x: "48%", y: "-36%", rotate: 0, scale: 1, z: 14 },
    entrance: { fromX: "115%", fromY: "0%", fromRotate: 10, glow: "orange" },
  },
  {
    id: "frame",
    label: "FRAME AI",
    accent: "frame",
    enterAt: APP_ENTRANCE_S.frame,
    imageSrc: "/intro/frame-ai.png",
    imageAlt: "Frame AI video editor generated by Vodex",
    desktop: { x: "-36%", y: "32%", rotate: 0, scale: 0.9, z: 16 },
    mobile: { x: "-48%", y: "36%", rotate: 0, scale: 1, z: 16 },
    entrance: { fromX: "-75%", fromY: "85%", fromRotate: 7, glow: "cyan" },
  },
  {
    id: "apex",
    label: "Apex Finance",
    accent: "apex",
    enterAt: APP_ENTRANCE_S.apex,
    imageSrc: "/intro/apex.png",
    imageAlt: "Apex Finance dashboard generated by Vodex",
    desktop: { x: "36%", y: "32%", rotate: 0, scale: 0.91, z: 18 },
    mobile: { x: "48%", y: "36%", rotate: 0, scale: 1, z: 18 },
    entrance: { fromX: "75%", fromY: "85%", fromRotate: -9, glow: "green" },
  },
];
