import { APP_ENTRANCE_S } from "@/components/session/intro/intro-constants";

export type IntroAppAccent = "nova" | "bite" | "frame" | "apex";

export type IntroAppConfig = {
  id: string;
  label: string;
  accent: IntroAppAccent;
  enterAt: number;
  imageSrc: string;
  imageAlt: string;
  desktop: { x: string; y: string; rotate: number; scale: number; z: number };
  mobile: { x: string; y: string; rotate: number; scale: number; z: number };
  entrance: {
    fromX: string;
    fromY: string;
    fromRotate: number;
    glow: string;
  };
};

/** Corner offsets use vw/vh so panels stay in quadrants (Framer % = element size, not viewport). */
export const INTRO_CINEMATIC_APPS: IntroAppConfig[] = [
  {
    id: "nova",
    label: "NOVA",
    accent: "nova",
    enterAt: APP_ENTRANCE_S.nova,
    imageSrc: "/intro/nova.png",
    imageAlt: "Nova fashion store generated by Vodex",
    desktop: { x: "-32vw", y: "-25vh", rotate: -6, scale: 0.9, z: 12 },
    mobile: { x: "-30vw", y: "-23vh", rotate: -4, scale: 0.84, z: 12 },
    entrance: { fromX: "-108vw", fromY: "-8vh", fromRotate: -14, glow: "purple" },
  },
  {
    id: "bite",
    label: "bite.",
    accent: "bite",
    enterAt: APP_ENTRANCE_S.bite,
    imageSrc: "/intro/bite.png",
    imageAlt: "Bite food delivery app generated by Vodex",
    desktop: { x: "32vw", y: "-23vh", rotate: 5, scale: 0.88, z: 14 },
    mobile: { x: "30vw", y: "-21vh", rotate: 4, scale: 0.82, z: 14 },
    entrance: { fromX: "108vw", fromY: "-6vh", fromRotate: 12, glow: "orange" },
  },
  {
    id: "frame",
    label: "FRAME AI",
    accent: "frame",
    enterAt: APP_ENTRANCE_S.frame,
    imageSrc: "/intro/frame-ai.png",
    imageAlt: "Frame AI video editor generated by Vodex",
    desktop: { x: "-30vw", y: "24vh", rotate: 4, scale: 0.86, z: 16 },
    mobile: { x: "-28vw", y: "22vh", rotate: 3, scale: 0.8, z: 16 },
    entrance: { fromX: "-92vw", fromY: "92vh", fromRotate: 9, glow: "cyan" },
  },
  {
    id: "apex",
    label: "Apex Finance",
    accent: "apex",
    enterAt: APP_ENTRANCE_S.apex,
    imageSrc: "/intro/apex.png",
    imageAlt: "Apex Finance dashboard generated by Vodex",
    desktop: { x: "30vw", y: "22vh", rotate: -5, scale: 0.87, z: 18 },
    mobile: { x: "28vw", y: "20vh", rotate: -4, scale: 0.81, z: 18 },
    entrance: { fromX: "92vw", fromY: "90vh", fromRotate: -11, glow: "green" },
  },
];
